# Generated by Django 4.2.16 on 2024-11-17 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('vehicle_count', models.IntegerField(default=0)),
                ('vehicle_types', models.JSONField(default=dict)),
                ('average_speed', models.FloatField(default=0.0)),
                ('congestion_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('incidents', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('speed', models.FloatField()),
                ('confidence', models.FloatField()),
                ('bbox_coordinates', models.JSONField()),
                ('traffic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='traffic_detection.trafficdata')),
            ],
        ),
    ]
